import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Explicit sidebars per category (labels and slugs taken from each category's _category_.json)
  talkSidebar: [
    {
      type: 'category',
      label: '个人向 WEB 与实用工具开发',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/talk/index',
        description: '或许只是工具的排列组合与 AI 的涌现, 但 Amusement is all you need',
      },
      items: [
        { type: 'autogenerated', dirName: 'talk' },
      ],
    },
  ],

  physSidebar: [
    {
      type: 'category',
      label: '物理学习',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/physics/index',
        description: '那些并不 Trival 的思考',
      },
      items: [
        { type: 'autogenerated', dirName: 'phys' },
      ],
    },
  ],

  jlptSidebar: [
    {
      type: 'category',
      label: '日语学习 与 JLPT',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/jlpt/index',
        description: 'Since 2018',
      },
      items: [
        { type: 'autogenerated', dirName: 'jlpt' },
      ],
    },
  ],

  chuniSidebar: [
    {
      type: 'category',
      label: '除你字母 2026',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/chuni/index',
        description: '绝对正义 ALL JUSTICE',
      },
      items: [
        { type: 'autogenerated', dirName: 'chuni' },
      ],
    },
  ],

  bgmSidebar: [
    {
      type: 'category',
      label: '阅番无数',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/bangumi/index',
        description: '点完一部 アニメ 的格子, 除了空虚还能留下什么',
      },
      items: [
        { type: 'autogenerated', dirName: 'bgm' },
      ],
    },
  ],

  traceSidebar: [
    {
      type: 'category',
      label: '旅迹追踪',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/trace/index',
        description: '风光、铁道、美食、以及打 call 逛展买本子',
      },
      items: [
        { type: 'autogenerated', dirName: 'trace' },
      ],
    },
  ],

  worksSidebar: [
    {
      type: 'category',
      label: 'ボカロ文化',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/vocaloid/index',
        description: '漫谈、体验、创作、分享',
      },
      items: [
        { type: 'autogenerated', dirName: 'works' },
      ],
    },
  ],

  // Fallback autogenerated sidebar for any other docs
  defaultSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
